server:
  port: 8801
eureka:
  instance:
    hostname: localhost
#    ip-address: 10.112.29.233
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false